cloud_to_laser_node:
  ros__parameters:
    # target_frame: lidar
    transform_tolerance: 0.01
    min_height: 0.0
    max_height: 1.0
    angle_min: -1.5707963267948966
    angle_max: 1.5707963267948966
    angle_increment: 0.0087
    # scan_time: 0.3333
    range_min: 2.5
    range_max: 100.0
    use_inf: True
